modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/zircky/GTR/issues"
[[mods]]
modId="gtceuadd"
version="${version}"
displayName="GTCEuAdd"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants"
#displayTest="MATCH_VERSION"
description='''

'''
[[dependencies.gtceuadd]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"


[[dependencies.gtceuadd]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.gtceuadd]]
modId = "geckolib"
mandatory = true
versionRange = "[4.2.1,)"
side = "BOTH"

[[dependencies.gtceuadd]]
modId = "gtceu"
mandatory = true
versionRange = "[1.4.6,)"
ordering = "BEFORE"
side = "BOTH"